name: Run PHPStan

on:
  push:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Run PHPStan
        uses: aragon999/phpstan-shopware-docker@master