name: PR Pipeline

on: [pull_request]

jobs:
  phpecs:
    name: Easy code standard
    runs-on: ubuntu-latest

    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: make dev -B

      - name: Run ecs
        run: make ecs -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: phpecs
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: make dev -B

      - name: Run PHP CS Fixer
        run: make csfix -B

  phpstan:
    name: Static Analyzers
    needs: phpcsfixer
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: make dev -B

      - name: Run PHPStan
        run: make stan -B

  phpunit:
    name: Unit Tests | PHP ${{ matrix.shopware }}
    needs: phpstan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '6.4.17.2' ]
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PROD Dependencies
        run: make install -B

      - name: Start Docker
        run: |
          docker run --rm --name shop -d dockware/dev:${{ matrix.shopware }}
          sleep 30
          docker logs shop
      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/SasEsd
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
      - name: Install and Build Plugin
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make clean'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make dev'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make phpunit'

  integration:
    name: Integration Tests | Shopware ${{ matrix.shopware }}
    needs: phpunit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '6.4.17.2',  '6.4.16.1', '6.4.15.2', '6.4.14.0', '6.4.12.0', '6.4.11.1', '6.4.10.0', '6.4.9.0', '6.4.8.2', '6.4.6.1',]
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PROD Dependencies
        run: make install -B

      - name: Start Docker
        run: |
          docker run --rm --name shop -d dockware/dev:${{ matrix.shopware }}
          sleep 30
          docker logs shop
      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/SasEsd
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
      - name: Install and Build Plugin
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make clean'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make install'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make build'