name: PackPlugin
on:
    push:
        branches:
            - master

jobs:
    integration:
        name: Integration Tests | Shopware ${{ matrix.shopware }} | PHP 8.1
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                shopware: [ '6.5.2.0', ]
        steps:
            - name: Clone Code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1

            - name: Start Docker
              run: |
                  docker run --rm --name shop --env PHP_VERSION=8.1 -d dockware/dev:${{ matrix.shopware }}
                  sleep 30
                  docker logs shop
            - name: Upload into Docker
              run: |
                  docker cp $(pwd)/. shop:/var/www/html/custom/plugins/SasEsd
                  docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
            - name: Install and Build Plugin
              run: |
                  docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make clean'
                  docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make install'
                  docker exec shop bash -c 'cd /var/www/html/custom/plugins/SasEsd && make build'

    build:
        uses: FriendsOfShopware/actions/.github/workflows/store-shopware-cli.yml@main
        with:
            extensionName: SasEsd
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}

